# 运行模式 dev/prod
#profile: prod
# 储气库 接口url
injectionUrl: https://www.eia.gov/dnav/ng/xls/NG_STOR_SUM_A_EPG0_SAI_MMCF_M.xls
# 液化天然气 接口url
withdrawUrl: https://www.eia.gov/dnav/ng/xls/NG_STOR_SUM_A_EPG0_SAW_MMCF_M.xls
# http代理
#proxy: http://10.22.96.29:8080
# 重复抓取的尝试次数
retryLimit: 12
# 重新抓取周期小时数
retryBeat: 20

# 数据库配置
host: 10.72.234.78
port: 1521
serviceName: ORCL
username: GAS
password: 123456
#host: localhost
#port: 1521
#serviceName: helowin
#username: scott
#password: scott
#host: 192.168.1.12
#port: 1521
#serviceName: ORCL
#username: GAS
#password: 123456
